name: RickySweum
favicon: null
layout_spectrum: 0.97964
typography_spectrum: 0.27014
title: 'Saxophonist, Composer, Educator, Producer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010207'
    - '#946749'
    - '#f4f7fc'
    - '#ebcabf'
    - '#b29492'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
