name: RickySweum
favicon: null
layout_spectrum: 0.5656192172318697
typography_spectrum: 0.6190473157912493
title: 'Saxophonist, Composer, Educator, Producer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.762583171017468
  lightness: 0.6734477572608739
  saturation: 0.10335178603418171
  rhythmicContrast: 0.6617421179544181
purpose: []
